name: Checks

on: [push]

jobs:
  test-lint:
    name : Testing and linting
    runs-on : ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name : Checkout
        uses: actions/checkout@v4
      - name : Bring up services
        run: docker compose up -d
        working-directory: ./ 
      - name : Run tests
        run: |
          docker compose run --rm api sh -c "python /app/manage.py wait_for_db && \
            python /app/manage.py migrate && \
            python /app/manage.py collectstatic --noinput && \
            python /app/manage.py test"
        working-directory: ./ 
      - name : Run lint
        run : docker compose run --rm api sh -c "flake8 /app"
        working-directory: ./ 
      - name : Tear down services
        run: docker compose down
        working-directory: ./ 
