name: Checks

on: [push]

jobs:
  test-lint:
    name: Testing and linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bring up services
        run: docker compose up -d

      - name: Run tests
        run: |
          docker compose run --rm api sh -c "python manage.py wait_for_db && \
          python manage.py migrate && \
          python manage.py collectstatic --noinput && \
          python manage.py test"

      - name: Run lint
        run: docker compose run --rm api sh -c "flake8 ."

      - name: Tear down services
        if: always()
        run: docker compose down
